const { uuid } = require('uuidv4');

const products = [
	{
		brand: "Amuse",
		image: "https://cosibella.com.ua/ukr_pm_Amuse-KREMOVI-RUMIANA-DLIA-OBLICHCHIA-Soft-Cream-Cheek-01-Sprinkles-3g-15736_1.webp",
		name: "Кремові рум'яна для обличчя - Soft Cream Cheek - 01 Sprinkles - 3g",
		rate: 4.5,
		price: 670,
		quantity: 1,
		id: uuid(),
		prop: "Кремові рум'яна у ніжно-рожевому відтінку",
		stock: false,
		category: "Акції",
		adult: true,
		weight: '3g',
		date: '12 місяців після відкриття',
		manufactr: 'Південна Корея',
		desc: "Amuse - Кремові рум'яна для обличчя -рум'яна для обличчя з кремовою формулою, які залишають сяючий оксамитовий фініш на шкірі. Мають невеликий аплікатор у формі зірки, який набирає необхідну кількість продукту. Засіб рівномірно розподіляється та не залишає відчуття липкості. Продукт веганський, довго тримається на шкірі.",
		contents: "Aqua, Cyclopentasiloxane, Methyl Trimethicone, CI 77019, Glycerin, PEG-10 Dimethicone, Methyl Methacrylate Crosspolymer, CI 77891, Dicaprylyl Carbonate, Disteardimonium Hectorite, Neopentyl Glycol Diheptanoate, Pentylene Glycol, Synthetic Fluorphlogopite, 1,2-Hexanediol, Sorbitan Isostearate, Vinyl Dimethicone/Methicone Silsesquioxane Crosspolymer, Magnesium Sulfate, Dimethicone/Vinyl Dimethicone Crosspolymer, Cetearyl Dimethicone/Vinyl Dimethicone Crosspolymer, Glyceryl Caprylate, Triethoxycaprylylsilane, Trisodium Ethylenediamine Disuccinate, Aluminum Hydroxide, Ascorbic Acid Polypeptide, Beta-Glucan, Tocopherol, CI 77861, Parfum, CI 73360, CI 77491, CI 77492, CI 77499, CI 77007",
		method: "Нанести невелику кількість засобу на щоки й розподілити пальцями.",
		liked: false
	 },
	 {
		brand: "Amuse",
		image: "https://cosibella.com.ua/ukr_pm_Amuse-KREMOVI-RUMIANA-DLIA-OBLICHCHIA-Soft-Cream-Cheek-01-Sprinkles-3g-15736_1.webp",
		name: "Кремові рум'яна для обличчя - Soft Cream Cheek - 01 Sprinkles - 3g",
		rate: 4.5,
		price: 670,
		quantity: 1,
		id: uuid(),
		prop: "Кремові рум'яна у ніжно-рожевому відтінку",
		stock: false,
		category: "Акції",
		liked: false,
		adult: false,
		weight: '3g',
		date: '12 місяців після відкриття',
		manufactr: 'Південна Корея',
		desc: "Amuse - Кремові рум'яна для обличчя -рум'яна для обличчя з кремовою формулою, які залишають сяючий оксамитовий фініш на шкірі. Мають невеликий аплікатор у формі зірки, який набирає необхідну кількість продукту. Засіб рівномірно розподіляється та не залишає відчуття липкості. Продукт веганський, довго тримається на шкірі.",
		contents: "Aqua, Cyclopentasiloxane, Methyl Trimethicone, CI 77019, Glycerin, PEG-10 Dimethicone, Methyl Methacrylate Crosspolymer, CI 77891, Dicaprylyl Carbonate, Disteardimonium Hectorite, Neopentyl Glycol Diheptanoate, Pentylene Glycol, Synthetic Fluorphlogopite, 1,2-Hexanediol, Sorbitan Isostearate, Vinyl Dimethicone/Methicone Silsesquioxane Crosspolymer, Magnesium Sulfate, Dimethicone/Vinyl Dimethicone Crosspolymer, Cetearyl Dimethicone/Vinyl Dimethicone Crosspolymer, Glyceryl Caprylate, Triethoxycaprylylsilane, Trisodium Ethylenediamine Disuccinate, Aluminum Hydroxide, Ascorbic Acid Polypeptide, Beta-Glucan, Tocopherol, CI 77861, Parfum, CI 73360, CI 77491, CI 77492, CI 77499, CI 77007",
		method: "Нанести невелику кількість засобу на щоки й розподілити пальцями.",
	 },
	 {
		brand: "Amuse",
		image: "https://cosibella.com.ua/ukr_pm_Amuse-KREMOVI-RUMIANA-DLIA-OBLICHCHIA-Soft-Cream-Cheek-01-Sprinkles-3g-15736_1.webp",
		name: "Кремові рум'яна для обличчя - Soft Cream Cheek - 01 Sprinkles - 3g",
		rate: 4.5,
		price: 670,
		quantity: 1,
		id: uuid(),
		prop: "Кремові рум'яна у ніжно-рожевому відтінку",
		stock: false,
		category: "Акції",
		adult: true,
		weight: '3g',
		date: '12 місяців після відкриття',
		manufactr: 'Південна Корея',
		desc: "Amuse - Кремові рум'яна для обличчя -рум'яна для обличчя з кремовою формулою, які залишають сяючий оксамитовий фініш на шкірі. Мають невеликий аплікатор у формі зірки, який набирає необхідну кількість продукту. Засіб рівномірно розподіляється та не залишає відчуття липкості. Продукт веганський, довго тримається на шкірі.",
		contents: "Aqua, Cyclopentasiloxane, Methyl Trimethicone, CI 77019, Glycerin, PEG-10 Dimethicone, Methyl Methacrylate Crosspolymer, CI 77891, Dicaprylyl Carbonate, Disteardimonium Hectorite, Neopentyl Glycol Diheptanoate, Pentylene Glycol, Synthetic Fluorphlogopite, 1,2-Hexanediol, Sorbitan Isostearate, Vinyl Dimethicone/Methicone Silsesquioxane Crosspolymer, Magnesium Sulfate, Dimethicone/Vinyl Dimethicone Crosspolymer, Cetearyl Dimethicone/Vinyl Dimethicone Crosspolymer, Glyceryl Caprylate, Triethoxycaprylylsilane, Trisodium Ethylenediamine Disuccinate, Aluminum Hydroxide, Ascorbic Acid Polypeptide, Beta-Glucan, Tocopherol, CI 77861, Parfum, CI 73360, CI 77491, CI 77492, CI 77499, CI 77007",
		method: "Нанести невелику кількість засобу на щоки й розподілити пальцями.",
		liked: false
	 },
	 {
		brand: "Amuse",
		image: "https://cosibella.com.ua/ukr_pm_Amuse-KREMOVI-RUMIANA-DLIA-OBLICHCHIA-Soft-Cream-Cheek-01-Sprinkles-3g-15736_1.webp",
		name: "Кремові рум'яна для обличчя - Soft Cream Cheek - 01 Sprinkles - 3g",
		rate: 4.5,
		price: 670,
		quantity: 1,
		id: uuid(),
		prop: "Кремові рум'яна у ніжно-рожевому відтінку",
		stock: false,
		category: "Акції",
		adult: true,
		weight: '3g',
		date: '12 місяців після відкриття',
		manufactr: 'Південна Корея',
		desc: "Amuse - Кремові рум'яна для обличчя -рум'яна для обличчя з кремовою формулою, які залишають сяючий оксамитовий фініш на шкірі. Мають невеликий аплікатор у формі зірки, який набирає необхідну кількість продукту. Засіб рівномірно розподіляється та не залишає відчуття липкості. Продукт веганський, довго тримається на шкірі.",
		contents: "Aqua, Cyclopentasiloxane, Methyl Trimethicone, CI 77019, Glycerin, PEG-10 Dimethicone, Methyl Methacrylate Crosspolymer, CI 77891, Dicaprylyl Carbonate, Disteardimonium Hectorite, Neopentyl Glycol Diheptanoate, Pentylene Glycol, Synthetic Fluorphlogopite, 1,2-Hexanediol, Sorbitan Isostearate, Vinyl Dimethicone/Methicone Silsesquioxane Crosspolymer, Magnesium Sulfate, Dimethicone/Vinyl Dimethicone Crosspolymer, Cetearyl Dimethicone/Vinyl Dimethicone Crosspolymer, Glyceryl Caprylate, Triethoxycaprylylsilane, Trisodium Ethylenediamine Disuccinate, Aluminum Hydroxide, Ascorbic Acid Polypeptide, Beta-Glucan, Tocopherol, CI 77861, Parfum, CI 73360, CI 77491, CI 77492, CI 77499, CI 77007",
		method: "Нанести невелику кількість засобу на щоки й розподілити пальцями.",
		liked: false
	 },
	 {
		brand: "A'pieu",
		image: "https://cosibella.com.ua/ukr_pm_Apieu-RIDKI-RUMIANA-DLIA-OBLICHCHIA-Juicy-Pang-Water-Blusher-PK04-9g-13640_1.webp",
		name: "Рідкі рум'яна для обличчя - Juicy-Pang Water Blusher - PK04 - 9g",
		rate: 4,
		price: 355,
		quantity: 1,
		id: uuid(),
		prop: "Рідкі рум'яна для обличчя у грейпфрутовому відтінку",
		stock: true,
		category: "Новинки",
		adult: false,
		weight: '9g',
		date: 'на упаковці.',
		manufactr: 'Південна Корея',
		desc: "A'pieu - Рідкі рум'яна для обличчя - рідкі рум'яна грейпфрутового кольору, які підкреслюють природний рум'янець. Залишають сатиновий фініш і мають легку водянисту консистенцію, яка дозволяє регулювати інтенсивність кольору. До складу косметичного засобу входять екстракт вишні, який є антиоксидантом, та олія гранатових кісточок, яка має зволожувальні й антивікові властивості. А олія жожоба регенерує шкіру, покращує її еластичність і пружність.",
		contents: "Aqua, Cyclopentasiloxane, Alcohol Denat., Butylene Glycol, Cetyl Ethylhexanoate, Methyl Trimethicone, Talc, Glycerin, Pentylene Glycol, PEG-10 Dimethicone, Triethylhexanoin, Synthetic Fluorphlogopite, Prunus Avium (Sweet Cherry) Fruit Extract, Rosa Damascena Flower Water, Ficus Carica (Fig) Fruit Extract, Citrus Aurantium Dulcis (Orange) Peel Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Camellia Oleifera Seed Oil, Nigella Sativa Seed Oil, Punica Granatum Seed Oil, Rosa Canina Fruit Oil, Vitis Vinifera (Grape) Fruit Extract, Prunus Armeniaca (Apricot) Fruit Extract, Vaccinium Angustifolium (Blueberry) Fruit Extract, Fragaria Chiloensis (Strawberry) Fruit Extract,Prunus Persica (Peach) Fruit Extract,Rubus Idaeus (Raspberry) Fruit Extract, Pyrus Malus (Apple) Fruit Extract, Citrus Aurantium Dulcis (Orange) Fruit Extract, Diospyros Kaki Fruit Extract, Juglans Regia (Walnut) Seed Extract, Morus Alba Fruit Extract, Punica Granatum Fruit Extract, Pyrus Communis (Pear) Fruit Extract, Solanum Lycopersicum (Tomato) Fruit Extract, Methyl Methacrylate Crosspolymer, Polypropylsilsesquioxane, Trimethylsiloxysilicate, Magnesium Sulfate, Cetyl PEG/PPG-10/1 Dimethicone, Disteardimonium Hectorite, Dimethicone, Dimethicone Crosspolymer, Triethoxycaprylylsilane, Ethylhexylglycerin, 1,2-Hexanediol, Caprylyl Glycol, Octanediol, Disodium EDTA, Phenoxyethanol, Parfum, Linalool, Limonene, Mica (CI 77019),I ron Oxides (CI 77491), Titanium Dioxide (CI 77891), Red 30 (CI 73360), Iron Oxides (CI 77492)",
		method: "Перед використанням струсити флакон. За допомогою аплікатора нанести невелику кількість рум'ян на щоки і розтушувати кінчиками пальців або спонжем.Перед першим використанням виконайте тест на алергію. Перевірте наш тест на алергію, щоб дізнатися більше.",
		liked: false
	 },
	 {
		brand: "A'pieu",
		image: "https://cosibella.com.ua/ukr_pm_Apieu-RIDKI-RUMIANA-DLIA-OBLICHCHIA-Juicy-Pang-Water-Blusher-PK04-9g-13640_1.webp",
		name: "Рідкі рум'яна для обличчя - Juicy-Pang Water Blusher - PK04 - 9g",
		rate: 4,
		price: 355,
		quantity: 1,
		id: uuid(),
		prop: "Рідкі рум'яна для обличчя у грейпфрутовому відтінку",
		stock: true,
		category: "Новинки",
		adult: false,
		weight: '9g',
		date: 'на упаковці.',
		manufactr: 'Південна Корея',
		desc: "A'pieu - Рідкі рум'яна для обличчя - рідкі рум'яна грейпфрутового кольору, які підкреслюють природний рум'янець. Залишають сатиновий фініш і мають легку водянисту консистенцію, яка дозволяє регулювати інтенсивність кольору. До складу косметичного засобу входять екстракт вишні, який є антиоксидантом, та олія гранатових кісточок, яка має зволожувальні й антивікові властивості. А олія жожоба регенерує шкіру, покращує її еластичність і пружність.",
		contents: "Aqua, Cyclopentasiloxane, Alcohol Denat., Butylene Glycol, Cetyl Ethylhexanoate, Methyl Trimethicone, Talc, Glycerin, Pentylene Glycol, PEG-10 Dimethicone, Triethylhexanoin, Synthetic Fluorphlogopite, Prunus Avium (Sweet Cherry) Fruit Extract, Rosa Damascena Flower Water, Ficus Carica (Fig) Fruit Extract, Citrus Aurantium Dulcis (Orange) Peel Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Camellia Oleifera Seed Oil, Nigella Sativa Seed Oil, Punica Granatum Seed Oil, Rosa Canina Fruit Oil, Vitis Vinifera (Grape) Fruit Extract, Prunus Armeniaca (Apricot) Fruit Extract, Vaccinium Angustifolium (Blueberry) Fruit Extract, Fragaria Chiloensis (Strawberry) Fruit Extract,Prunus Persica (Peach) Fruit Extract,Rubus Idaeus (Raspberry) Fruit Extract, Pyrus Malus (Apple) Fruit Extract, Citrus Aurantium Dulcis (Orange) Fruit Extract, Diospyros Kaki Fruit Extract, Juglans Regia (Walnut) Seed Extract, Morus Alba Fruit Extract, Punica Granatum Fruit Extract, Pyrus Communis (Pear) Fruit Extract, Solanum Lycopersicum (Tomato) Fruit Extract, Methyl Methacrylate Crosspolymer, Polypropylsilsesquioxane, Trimethylsiloxysilicate, Magnesium Sulfate, Cetyl PEG/PPG-10/1 Dimethicone, Disteardimonium Hectorite, Dimethicone, Dimethicone Crosspolymer, Triethoxycaprylylsilane, Ethylhexylglycerin, 1,2-Hexanediol, Caprylyl Glycol, Octanediol, Disodium EDTA, Phenoxyethanol, Parfum, Linalool, Limonene, Mica (CI 77019),I ron Oxides (CI 77491), Titanium Dioxide (CI 77891), Red 30 (CI 73360), Iron Oxides (CI 77492)",
		method: "Перед використанням струсити флакон. За допомогою аплікатора нанести невелику кількість рум'ян на щоки і розтушувати кінчиками пальців або спонжем.Перед першим використанням виконайте тест на алергію. Перевірте наш тест на алергію, щоб дізнатися більше.",
		liked: false
	 },
	 {
		brand: "A'pieu",
		image: "https://cosibella.com.ua/ukr_pm_Apieu-RIDKI-RUMIANA-DLIA-OBLICHCHIA-Juicy-Pang-Water-Blusher-PK04-9g-13640_1.webp",
		name: "Рідкі рум'яна для обличчя - Juicy-Pang Water Blusher - PK04 - 9g",
		rate: 4,
		price: 355,
		quantity: 1,
		id: uuid(),
		prop: "Рідкі рум'яна для обличчя у грейпфрутовому відтінку",
		stock: true,
		category: "Новинки",
		adult: false,
		weight: '9g',
		date: 'на упаковці.',
		manufactr: 'Південна Корея',
		desc: "A'pieu - Рідкі рум'яна для обличчя - рідкі рум'яна грейпфрутового кольору, які підкреслюють природний рум'янець. Залишають сатиновий фініш і мають легку водянисту консистенцію, яка дозволяє регулювати інтенсивність кольору. До складу косметичного засобу входять екстракт вишні, який є антиоксидантом, та олія гранатових кісточок, яка має зволожувальні й антивікові властивості. А олія жожоба регенерує шкіру, покращує її еластичність і пружність.",
		contents: "Aqua, Cyclopentasiloxane, Alcohol Denat., Butylene Glycol, Cetyl Ethylhexanoate, Methyl Trimethicone, Talc, Glycerin, Pentylene Glycol, PEG-10 Dimethicone, Triethylhexanoin, Synthetic Fluorphlogopite, Prunus Avium (Sweet Cherry) Fruit Extract, Rosa Damascena Flower Water, Ficus Carica (Fig) Fruit Extract, Citrus Aurantium Dulcis (Orange) Peel Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Camellia Oleifera Seed Oil, Nigella Sativa Seed Oil, Punica Granatum Seed Oil, Rosa Canina Fruit Oil, Vitis Vinifera (Grape) Fruit Extract, Prunus Armeniaca (Apricot) Fruit Extract, Vaccinium Angustifolium (Blueberry) Fruit Extract, Fragaria Chiloensis (Strawberry) Fruit Extract,Prunus Persica (Peach) Fruit Extract,Rubus Idaeus (Raspberry) Fruit Extract, Pyrus Malus (Apple) Fruit Extract, Citrus Aurantium Dulcis (Orange) Fruit Extract, Diospyros Kaki Fruit Extract, Juglans Regia (Walnut) Seed Extract, Morus Alba Fruit Extract, Punica Granatum Fruit Extract, Pyrus Communis (Pear) Fruit Extract, Solanum Lycopersicum (Tomato) Fruit Extract, Methyl Methacrylate Crosspolymer, Polypropylsilsesquioxane, Trimethylsiloxysilicate, Magnesium Sulfate, Cetyl PEG/PPG-10/1 Dimethicone, Disteardimonium Hectorite, Dimethicone, Dimethicone Crosspolymer, Triethoxycaprylylsilane, Ethylhexylglycerin, 1,2-Hexanediol, Caprylyl Glycol, Octanediol, Disodium EDTA, Phenoxyethanol, Parfum, Linalool, Limonene, Mica (CI 77019),I ron Oxides (CI 77491), Titanium Dioxide (CI 77891), Red 30 (CI 73360), Iron Oxides (CI 77492)",
		method: "Перед використанням струсити флакон. За допомогою аплікатора нанести невелику кількість рум'ян на щоки і розтушувати кінчиками пальців або спонжем.Перед першим використанням виконайте тест на алергію. Перевірте наш тест на алергію, щоб дізнатися більше.",
		liked: false
	 },
	 {
		brand: "A'pieu",
		image: "https://cosibella.com.ua/ukr_pm_Apieu-RIDKI-RUMIANA-DLIA-OBLICHCHIA-Juicy-Pang-Water-Blusher-PK04-9g-13640_1.webp",
		name: "Рідкі рум'яна для обличчя - Juicy-Pang Water Blusher - PK04 - 9g",
		rate: 4,
		price: 355,
		quantity: 1,
		id: uuid(),
		prop: "Рідкі рум'яна для обличчя у грейпфрутовому відтінку",
		stock: true,
		category: "Новинки",
		adult: false,
		weight: '9g',
		date: 'на упаковці.',
		manufactr: 'Південна Корея',
		desc: "A'pieu - Рідкі рум'яна для обличчя - рідкі рум'яна грейпфрутового кольору, які підкреслюють природний рум'янець. Залишають сатиновий фініш і мають легку водянисту консистенцію, яка дозволяє регулювати інтенсивність кольору. До складу косметичного засобу входять екстракт вишні, який є антиоксидантом, та олія гранатових кісточок, яка має зволожувальні й антивікові властивості. А олія жожоба регенерує шкіру, покращує її еластичність і пружність.",
		contents: "Aqua, Cyclopentasiloxane, Alcohol Denat., Butylene Glycol, Cetyl Ethylhexanoate, Methyl Trimethicone, Talc, Glycerin, Pentylene Glycol, PEG-10 Dimethicone, Triethylhexanoin, Synthetic Fluorphlogopite, Prunus Avium (Sweet Cherry) Fruit Extract, Rosa Damascena Flower Water, Ficus Carica (Fig) Fruit Extract, Citrus Aurantium Dulcis (Orange) Peel Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Camellia Oleifera Seed Oil, Nigella Sativa Seed Oil, Punica Granatum Seed Oil, Rosa Canina Fruit Oil, Vitis Vinifera (Grape) Fruit Extract, Prunus Armeniaca (Apricot) Fruit Extract, Vaccinium Angustifolium (Blueberry) Fruit Extract, Fragaria Chiloensis (Strawberry) Fruit Extract,Prunus Persica (Peach) Fruit Extract,Rubus Idaeus (Raspberry) Fruit Extract, Pyrus Malus (Apple) Fruit Extract, Citrus Aurantium Dulcis (Orange) Fruit Extract, Diospyros Kaki Fruit Extract, Juglans Regia (Walnut) Seed Extract, Morus Alba Fruit Extract, Punica Granatum Fruit Extract, Pyrus Communis (Pear) Fruit Extract, Solanum Lycopersicum (Tomato) Fruit Extract, Methyl Methacrylate Crosspolymer, Polypropylsilsesquioxane, Trimethylsiloxysilicate, Magnesium Sulfate, Cetyl PEG/PPG-10/1 Dimethicone, Disteardimonium Hectorite, Dimethicone, Dimethicone Crosspolymer, Triethoxycaprylylsilane, Ethylhexylglycerin, 1,2-Hexanediol, Caprylyl Glycol, Octanediol, Disodium EDTA, Phenoxyethanol, Parfum, Linalool, Limonene, Mica (CI 77019),I ron Oxides (CI 77491), Titanium Dioxide (CI 77891), Red 30 (CI 73360), Iron Oxides (CI 77492)",
		method: "Перед використанням струсити флакон. За допомогою аплікатора нанести невелику кількість рум'ян на щоки і розтушувати кінчиками пальців або спонжем.Перед першим використанням виконайте тест на алергію. Перевірте наш тест на алергію, щоб дізнатися більше.",
		liked: false
	 },
	 {
		brand: "A'pieu",
		image: "https://cosibella.com.ua/ukr_pm_Apieu-RIDKI-RUMIANA-DLIA-OBLICHCHIA-Juicy-Pang-Water-Blusher-PK04-9g-13640_1.webp",
		name: "Рідкі рум'яна для обличчя - Juicy-Pang Water Blusher - PK04 - 9g",
		rate: 4,
		price: 355,
		quantity: 1,
		id: uuid(),
		prop: "Рідкі рум'яна для обличчя у грейпфрутовому відтінку",
		stock: true,
		category: "Новинки",
		adult: false,
		weight: '9g',
		date: 'на упаковці.',
		manufactr: 'Південна Корея',
		desc: "A'pieu - Рідкі рум'яна для обличчя - рідкі рум'яна грейпфрутового кольору, які підкреслюють природний рум'янець. Залишають сатиновий фініш і мають легку водянисту консистенцію, яка дозволяє регулювати інтенсивність кольору. До складу косметичного засобу входять екстракт вишні, який є антиоксидантом, та олія гранатових кісточок, яка має зволожувальні й антивікові властивості. А олія жожоба регенерує шкіру, покращує її еластичність і пружність.",
		contents: "Aqua, Cyclopentasiloxane, Alcohol Denat., Butylene Glycol, Cetyl Ethylhexanoate, Methyl Trimethicone, Talc, Glycerin, Pentylene Glycol, PEG-10 Dimethicone, Triethylhexanoin, Synthetic Fluorphlogopite, Prunus Avium (Sweet Cherry) Fruit Extract, Rosa Damascena Flower Water, Ficus Carica (Fig) Fruit Extract, Citrus Aurantium Dulcis (Orange) Peel Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Camellia Oleifera Seed Oil, Nigella Sativa Seed Oil, Punica Granatum Seed Oil, Rosa Canina Fruit Oil, Vitis Vinifera (Grape) Fruit Extract, Prunus Armeniaca (Apricot) Fruit Extract, Vaccinium Angustifolium (Blueberry) Fruit Extract, Fragaria Chiloensis (Strawberry) Fruit Extract,Prunus Persica (Peach) Fruit Extract,Rubus Idaeus (Raspberry) Fruit Extract, Pyrus Malus (Apple) Fruit Extract, Citrus Aurantium Dulcis (Orange) Fruit Extract, Diospyros Kaki Fruit Extract, Juglans Regia (Walnut) Seed Extract, Morus Alba Fruit Extract, Punica Granatum Fruit Extract, Pyrus Communis (Pear) Fruit Extract, Solanum Lycopersicum (Tomato) Fruit Extract, Methyl Methacrylate Crosspolymer, Polypropylsilsesquioxane, Trimethylsiloxysilicate, Magnesium Sulfate, Cetyl PEG/PPG-10/1 Dimethicone, Disteardimonium Hectorite, Dimethicone, Dimethicone Crosspolymer, Triethoxycaprylylsilane, Ethylhexylglycerin, 1,2-Hexanediol, Caprylyl Glycol, Octanediol, Disodium EDTA, Phenoxyethanol, Parfum, Linalool, Limonene, Mica (CI 77019),I ron Oxides (CI 77491), Titanium Dioxide (CI 77891), Red 30 (CI 73360), Iron Oxides (CI 77492)",
		method: "Перед використанням струсити флакон. За допомогою аплікатора нанести невелику кількість рум'ян на щоки і розтушувати кінчиками пальців або спонжем.Перед першим використанням виконайте тест на алергію. Перевірте наш тест на алергію, щоб дізнатися більше.",
		liked: false
	 },
	 {
		brand: "Affect",
		image: "https://cosibella.com.ua/ukr_pm_Affect-Eyebrow-Pomade-Waterproof-Light-VODOSTIIKA-POMADA-DLIA-BRIV-5g-2388_1.webp",
		name: "Eyebrow Pomade Waterproof - Light - Водостійка помада для брів - 5g",
		rate: 5,
		price: 225,
		quantity: 1,
		id: uuid(),
		prop: "Надає бровам потрібну форму і колір",
		stock: true,
		category: "Бестселери",
		adult: true,
		weight: '5g',
		date: '6 місяців після відкриття',
		manufactr: 'Польща',
		desc: "Affect - Eyebrow Pomade Waterproof - Light - водостійка помада, яка надає бровам потрібну форму і колір. Завдяки кремовій текстурі легко наноситься і тушується. Стійка і сильно пігментована. Доступна в трьох натуральних відтінках.",
		contents: "C12-15 Alkyl Benzoate, Trimethylsiloxysilicate, Titanium Dioxide, Paraffinum Liquidum, Cyclopentasiloxane, Dimethylimidazolidone Rice Starch, Nylon-12, Polyethylene, Bis-Stearyl, Dimethicone, Lauroyl Lysine, Polymethylsilsesquioxane, Cera Alba, Copernica Cerifera Cera, Polytetrafluoroethylene, Syntetic Wax, HDI/Trimethylol Hexyllactone Crosspolymer, Phenoxyethanol, Ethylhexylglycerin/ +/- C I 77499, C I 77492, C I 77491 /",
		liked: false
	 },
	 {
		brand: "Affect",
		image: "https://cosibella.com.ua/ukr_pm_Affect-Eyebrow-Pomade-Waterproof-Light-VODOSTIIKA-POMADA-DLIA-BRIV-5g-2388_1.webp",
		name: "Eyebrow Pomade Waterproof - Light - Водостійка помада для брів - 5g",
		rate: 5,
		price: 225,
		quantity: 1,
		id: uuid(),
		prop: "Надає бровам потрібну форму і колір",
		stock: true,
		category: "Бестселери",
		adult: true,
		weight: '5g',
		date: '6 місяців після відкриття',
		manufactr: 'Польща',
		desc: "Affect - Eyebrow Pomade Waterproof - Light - водостійка помада, яка надає бровам потрібну форму і колір. Завдяки кремовій текстурі легко наноситься і тушується. Стійка і сильно пігментована. Доступна в трьох натуральних відтінках.",
		contents: "C12-15 Alkyl Benzoate, Trimethylsiloxysilicate, Titanium Dioxide, Paraffinum Liquidum, Cyclopentasiloxane, Dimethylimidazolidone Rice Starch, Nylon-12, Polyethylene, Bis-Stearyl, Dimethicone, Lauroyl Lysine, Polymethylsilsesquioxane, Cera Alba, Copernica Cerifera Cera, Polytetrafluoroethylene, Syntetic Wax, HDI/Trimethylol Hexyllactone Crosspolymer, Phenoxyethanol, Ethylhexylglycerin/ +/- C I 77499, C I 77492, C I 77491 /",
		liked: false
	 },
	 {
		brand: "Affect",
		image: "https://cosibella.com.ua/ukr_pm_Affect-Eyebrow-Pomade-Waterproof-Light-VODOSTIIKA-POMADA-DLIA-BRIV-5g-2388_1.webp",
		name: "Eyebrow Pomade Waterproof - Light - Водостійка помада для брів - 5g",
		rate: 5,
		price: 225,
		quantity: 1,
		id: uuid(),
		prop: "Надає бровам потрібну форму і колір",
		stock: true,
		category: "Бестселери",
		adult: true,
		weight: '5g',
		date: '6 місяців після відкриття',
		manufactr: 'Польща',
		desc: "Affect - Eyebrow Pomade Waterproof - Light - водостійка помада, яка надає бровам потрібну форму і колір. Завдяки кремовій текстурі легко наноситься і тушується. Стійка і сильно пігментована. Доступна в трьох натуральних відтінках.",
		contents: "C12-15 Alkyl Benzoate, Trimethylsiloxysilicate, Titanium Dioxide, Paraffinum Liquidum, Cyclopentasiloxane, Dimethylimidazolidone Rice Starch, Nylon-12, Polyethylene, Bis-Stearyl, Dimethicone, Lauroyl Lysine, Polymethylsilsesquioxane, Cera Alba, Copernica Cerifera Cera, Polytetrafluoroethylene, Syntetic Wax, HDI/Trimethylol Hexyllactone Crosspolymer, Phenoxyethanol, Ethylhexylglycerin/ +/- C I 77499, C I 77492, C I 77491 /",
		liked: false
	 },
	 {
		brand: "Affect",
		image: "https://cosibella.com.ua/ukr_pm_Affect-Eyebrow-Pomade-Waterproof-Light-VODOSTIIKA-POMADA-DLIA-BRIV-5g-2388_1.webp",
		name: "Eyebrow Pomade Waterproof - Light - Водостійка помада для брів - 5g",
		rate: 5,
		price: 225,
		quantity: 1,
		id: uuid(),
		prop: "Надає бровам потрібну форму і колір",
		stock: true,
		category: "Бестселери",
		adult: true,
		weight: '5g',
		date: '6 місяців після відкриття',
		manufactr: 'Польща',
		desc: "Affect - Eyebrow Pomade Waterproof - Light - водостійка помада, яка надає бровам потрібну форму і колір. Завдяки кремовій текстурі легко наноситься і тушується. Стійка і сильно пігментована. Доступна в трьох натуральних відтінках.",
		contents: "C12-15 Alkyl Benzoate, Trimethylsiloxysilicate, Titanium Dioxide, Paraffinum Liquidum, Cyclopentasiloxane, Dimethylimidazolidone Rice Starch, Nylon-12, Polyethylene, Bis-Stearyl, Dimethicone, Lauroyl Lysine, Polymethylsilsesquioxane, Cera Alba, Copernica Cerifera Cera, Polytetrafluoroethylene, Syntetic Wax, HDI/Trimethylol Hexyllactone Crosspolymer, Phenoxyethanol, Ethylhexylglycerin/ +/- C I 77499, C I 77492, C I 77491 /",
		liked: false
	 },
]

module.exports = products